[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://lottery-system-tna9.onrender.com"
  REACT_APP_API_VERSION = "v1"
  REACT_APP_VERSION = "1.0.0"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
