version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: newbetting-db
    environment:
      POSTGRES_DB: newbetting
      POSTGRES_USER: newbetting
      POSTGRES_PASSWORD: newbetting123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - newbetting-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: newbetting-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://newbetting:newbetting123@postgres:5432/newbetting
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      PORT: 3000
      TZ: Asia/Manila
      CORS_ORIGIN: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - newbetting-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newbetting-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
      REACT_APP_SOCKET_URL: http://localhost:3000
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - newbetting-network
    restart: unless-stopped

  # Redis (for session storage and caching)
  redis:
    image: redis:7-alpine
    container_name: newbetting-redis
    ports:
      - "6379:6379"
    networks:
      - newbetting-network
    restart: unless-stopped
    volumes:
      - redis_data:/data

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: newbetting-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - newbetting-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  newbetting-network:
    driver: bridge




