services:
  - type: web
    name: lottery-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node start-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lottery-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://lottery-system-gamma.vercel.app
    healthCheckPath: /api/v1/health

databases:
  - name: lottery-db
    plan: free
