services:
  - type: web
    name: lottery-backend
    runtime: node
    plan: free
    buildCommand: npm install && node setup-database.js
    startCommand: node start-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lottery-db
          property: connectionString
    healthCheckPath: /api/v1/health

databases:
  - name: lottery-db
    databaseName: lottery_db
    user: lottery_user
    plan: free
