services:
  - type: web
    name: lottery-backend
    runtime: node
    plan: free
    buildCommand: npm install && node setup-database.js
    startCommand: node start-server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/v1/health

databases:
  - name: lottery-db
    plan: free
